### ISSUE TITLE
guacmole probleme

### ISSUE THREAD

**Issue by v3rlust** [jimmy201602/webterminal#26]
Actually i had a problem after connecting to server and do what ever i want 
and when i close the connection there is no replay or i see the line of replay but no replays was found  
and a an error is finded in runserver console with : 

``[2018/03/29 09:07:07] HTTP GET /guacamole/2/ 200 [0.02, 192.168.1.100:51844]
[2018/03/29 09:07:07] WebSocket HANDSHAKING /guacamole/2/ [192.168.1.100:51845]
[2018/03/29 09:07:07] WebSocket CONNECT /guacamole/2/ [192.168.1.100:51845]
[2018/03/29 09:09:51] WebSocket DISCONNECT /guacamole/2/ [192.168.1.100:51845]
disconnect
[2018/03/29 09:09:51] HTTP POST /sshterminalkill/ 200 [0.06, 192.168.1.100:51848]
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/opt/webterminal/guacamole/guacamolethreading.py", line 54, in run
    instruction = self.client.receive()
  File "/opt/webterminal/guacamole/client.py", line 109, in receive
    buf = self.client.recv(BUF_LEN)
timeout: timed out
``

this is the first probleme 
the second probleme how users that i add it can connect because whene i try to add user it add normally but whene he try to connect from a django administration page it said sorry this only for staff_team something like that
and when i give him a staff_team member he can do everything to the other users he can delet them and add permission to them ................ 
 please give me answers

**Comment by jimmy201602** [comment]
The first problem is just a normal exception. It won't affect your action.
The second problem is just caused the permission control system. For now I haven't finished it yet. So just wait for the next release.

**Comment by botti007** [comment]
actually it s not a normal exception because 
it didn t record the session that i make it

**Comment by botti007** [comment]
and i had the same problem of this sir

**Comment by v3rlust** [comment]
for the first issue and exception i think it wasn't normal because i can see the record line in log info but when i click on replay there is no replay so there is a problem
