### ISSUE TITLE
Replay doesn't work

### ISSUE THREAD

**Issue by v3rlust** [jimmy201602/webterminal#27]
sorry bro for asking too match but i really need you'r project in my company and the replay doesn't work for me and add the permission to see the log info and nothing happen i stay click on play  and nothing
reader appear but no screen recorded this erreur happen can you help me and you said it's normal : 
`Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/opt/webterminal/guacamole/guacamolethreading.py", line 54, in run
    instruction = self.client.receive()
  File "/opt/webterminal/guacamole/client.py", line 109, in receive
    buf = self.client.recv(BUF_LEN)
timeout: timed out

`
this erreur when i disconnect and no other erreur happen 
`[2018/03/29 18:14:55] HTTP GET /guacamole/logplay/1/ 200 [0.06, 192.168.1.12:55849]
[2018/03/29 18:14:55] HTTP GET /static/css/playback.css 304 [0.02, 192.168.1.12:55849]
[2018/03/29 18:14:55] HTTP GET /static/plugins/guacamole/all.min.js?_=1522347292672 200 [0.02, 192.168.1.12:55851]
[2018/03/29 18:14:55] HTTP GET /static/plugins/guacamole/playback.js?_=1522347292673 200 [0.02, 192.168.1.12:55851]
Not Found: /media/2018-3-29/1135d31a-f2b3-47cf-b1c9-630ad3e330eb
[2018/03/29 18:14:55] HTTP GET /media/2018-3-29/1135d31a-f2b3-47cf-b1c9-630ad3e330eb 404 [0.05, 192.168.1.12:55851]
`

please help me :D 
 
the replay work with ssh but rdp no

**Comment by jimmy201602** [comment]
According to your description. I think you just use the very old instruction to install this project. So actually the recording file hadn't been created. I see these logs.
```sh
Not Found: /media/2018-3-29/1135d31a-f2b3-47cf-b1c9-630ad3e330eb
[2018/03/29 18:14:55] HTTP GET /media/2018-3-29/1135d31a-f2b3-47cf-b1c9-630ad3e330eb 404 [0.05, 192.168.1.12:55851]
```
Please make sure you have installed the gucad and the webterminal project on the same environment.
Any comment will appreciate. If you has any questions you can contact me. My email is zhengge2012@gmail.com.

**Comment by jimmy201602** [comment]
I just review my installation instruction. I found that's my fault. Lately I will update the installation document.

**Comment by v3rlust** [comment]
actually  i installed guacd in docker container like u said :D and the replay for ssh works fine however rdp and vnc no !
we are whaiting for an english installation update to solve that problem 
also  we are waiting to make a normal user gui to user that aren't admin 
i hope that u solve the problem and really thank you so much

**Comment by jimmy201602** [comment]
Thanks for your suggestion. I just update the document. Then you can follow it.
In the next release I will consider the UI and user experience staff...
Maybe in the next month... I will finish it. If you like this project. You can join the development. It will speed up the progress.
