### ISSUE TITLE
Not  able to run

### ISSUE THREAD

**Issue by vinokumark** [jimmy201602/webterminal#38]
./manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fabab4a0620>
Traceback (most recent call last):
  File "/home/vino/py3/lib/python3.5/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/vino/py3/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/home/vino/py3/lib/python3.5/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/home/vino/py3/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/vino/py3/lib/python3.5/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/vino/py3/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vino/py3/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/vino/py3/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/vino/py3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/vino/scripts/webterminal/elfinder/models.py", line 2, in <module>
    from elfinder.fields import ElfinderField 
  File "/home/vino/scripts/webterminal/elfinder/fields.py", line 6, in <module>
    from utils.volumes import get_path_driver
  File "/home/vino/scripts/webterminal/elfinder/utils/volumes.py", line 3, in <module>
    from elfinder.conf import settings as ls 
  File "/home/vino/scripts/webterminal/elfinder/conf/settings.py", line 4, in <module>
    from elfinder.volumes.filesystem import ElfinderVolumeLocalFileSystem
  File "/home/vino/scripts/webterminal/elfinder/volumes/filesystem.py", line 29
    self._options['dirMode']  = 0755 #new dirs mode
                                   ^
SyntaxError: invalid token

**Comment by jimmy201602** [comment]
python3 not compatible
