### ISSUE TITLE
python2 posix_shell方法中在对部分中文编码通过u()方法转成unicode会触发报错

### ISSUE THREAD

**Issue by grub007** [jimmy201602/webterminal#68]
错误详情如下:
2019-01-29 01:57:40,347 [Thread-103:139751908353792] [webterminal_logger:154] [WARNING]- Traceback (most recent call last):
  File "/opt/ncm_proj/ncm_sync/apps/webterminal/interactive.py", line 152, in posix_shell
    x = u(x)
  File "/usr/local/lib/python2.7/site-packages/paramiko/py3compat.py", line 70, in u
    return s.decode(encoding)
  File "/usr/local/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe8 in position 0: unexpected end of data

**Comment by jimmy201602** [comment]
Try to use docker tag beta (webterminal/webterminal:beta)
